### ISSUE TITLE
Multiple TextFields.

### ISSUE THREAD

**Issue by hugocarlmartin** [mnbayan/AutocompleteTextfieldSwift#11]
Greate component. I have  a small problem.

Lets say I have 3 textfields I'm populating with `autoCompleteStrings = [String]`. And on textchange everything works as it should.

But I also have 2 textFields I would like the tableview to function as a "picker" instead. So when the specific textField `becomeFirstResponder` i would like to populate the tableView with strings and the one on `[String][0]` should be pre-filled in the textField.

Edit: I can't seem to hide one textFields tableView when another textField `becomeFirstResponer`

Does it make sense?

Pre-Salamat, ;)

**Comment by mnbayan** [comment]
Hi @hugocarlmartin , you can actually do that by setting `textField.text = [String][0]` right after you populated `autoCompleteStrings`

And hiding suggestions when another textField was selected has been added. Thanks for reporting.
