### ISSUE TITLE
Tableview not scrolling

### ISSUE THREAD

**Issue by tejas-ardeshna** [mnbayan/AutocompleteTextfieldSwift#14]
I have integrated all properties of AutocompleteTextfieldSwift, and dropdown is working fine. But i can't scroll or select any row of tableview(dropdown)

**Comment by Narayane** [comment]
+1

didSelectRowAtIndexPath never fired

**Comment by Kdoherty11** [comment]
I fixed this by removing a UITapGestureRecognizer I had put on my view to dismiss the keyboard
