### ISSUE TITLE
Clinking 2nd or 3rd item in dropdown table doesn't call onSelect

### ISSUE THREAD

**Issue by pawannimje** [mnbayan/AutocompleteTextfieldSwift#18]
I have a signup form and I am using this AutocompleteTextfield. But when I click on 2nd or 3rd Item, onSelect is not called, it is only called for 1st Item click.

I am guessing, I am seeing this issue because behind 2nd and 3rd item, I have my own fields.

**Comment by mnbayan** [comment]
Hi @pawannimje  , i wasn't able to replicate this issue. But I have updated the code for the latest swift version. Please try if this will work for you first. Thank you.

**Comment by wvdk** [comment]
I also was not able to replicate this issue. Working fine for me.

**Comment by mnbayan** [comment]
@wvdk thanks for the feedback.

@pawannimje are you able to find out what cause this on your end?

**Comment by pkc456** [comment]
Today, I encounter with similar kind of issue. I open an issue. Please check issue #57 .
