### ISSUE TITLE
onSelect never gets called

### ISSUE THREAD

**Issue by lydemann** [mnbayan/AutocompleteTextfieldSwift#19]
With default configurations onSelect never gets called when selecting a dropdown element.

**Comment by lydemann** [comment]
The issue was solved by removing

public override func resignFirstResponder() -> Bool {
        self.autoCompleteTableView?.hidden = true

```
    return super.resignFirstResponder()
```

}

**Comment by alex-swiftify** [comment]
I confirm the problem.
lydemeister: I think we should remove resignFirstResponder override, otherwise didSelectRowAtIndexPath doesn't get called.
