### ISSUE TITLE
EXC_BAD_ACCESS when trying to use any property

### ISSUE THREAD

**Issue by wasimxyz** [mnbayan/AutocompleteTextfieldSwift#28]
I'm trying to use properties such as autoCompleteStrings and onTextChange with my AutoCompleteTextField, but every time the app runs, it crashes and gives me an EXC_BAD_ACCESS error code. I can't figure out why. The app runs perfectly if I don't set any properties. Any ideas?

**Comment by wasimxyz** [comment]
never mind lmao

**Comment by AshkanImmortal** [comment]
Have same issue, how you fixed that?

**Comment by mjmarathon** [comment]
It's probably because the textfield outlet was marked as an AutoCompleteTextField in the class that attempts to set the properties but was not set as the class for the textfield in the storyboard.

**Comment by AshkanImmortal** [comment]
Right, thank you
