### ISSUE TITLE
Location Bias

### ISSUE THREAD

**Issue by AcriCAA** [mnbayan/AutocompleteTextfieldSwift#33]
@mnbayan 

Hi, 

I am wondering if or how you can add Google's location bias parameter to this? 

https://developers.google.com/places/web-service/autocomplete#location_biasing

Thanks

**Comment by mnbayan** [comment]
HI @AcriCAA , you can do completely what you want with the request, what the library does is display the strings you passed.

Sorry, this reply is late but i hope i was able to help. Thanks!

**Comment by DavidCollinsNZ** [comment]
@AcriCAA You can modify the request URL string to include the GPS co-ordinates and radius.
