### ISSUE TITLE
Wrong place into the frame

### ISSUE THREAD

**Issue by ignacio-chiazzo** [mnbayan/AutocompleteTextfieldSwift#43]
The function setupAutocompleteTable is not calculating the right place. 
I pass a subview that is into a subview, and the frame is calculated improperly, I had to overwrite the function in order to fix this issue.

Is there an update to that fix? If not when I finish I will submit my solution.

**Comment by omerbas92** [comment]
Could you fix it? I have same problem too.

**Comment by b-e-r-t-o** [comment]
@ignacio-chiazzo any updates?

**Comment by ignacio-chiazzo** [comment]
@omerbas92 @b-e-r-t-o I am busy now, I'll do it ASAIC.

**Comment by suyashb734** [comment]
Remove the code that is in awakefromnib, override the method layoutSubviews and put it there - it then works

**Comment by ignacio-chiazzo** [comment]
Closing this,
