### ISSUE TITLE
how to custom autoCompleteCellWidth?

### ISSUE THREAD

**Issue by aotian16** [mnbayan/AutocompleteTextfieldSwift#5]
I can set height with autoCompleteCellHeight,
but i can't set width.
It's seem that there is no autoCompleteCellWidth?

**Comment by mnbayan** [comment]
@aotian16 i did not provide autoCompleteCellWidth. The cell width will be based on the tableview width, (notice that there is no delegate method that is called `widthForRow:atIndexPath` as oppose to `heightForRow:atIndexPath`) and in this library, the tableview is ALWAYS the same width as the textfield.

**Comment by aotian16** [comment]
Thanks for your comment.
But in my project, the tableview is the same width as the screen width, not as the textfield.
The textfield i use is about half width of screen width.

I fix this in **setupTableView** method

source like this

let tableView = UITableView(frame: CGRectMake(self.frame.origin.x, self.frame.origin.y + CGRectGetHeight(self.frame), **CGRectGetWidth(self.frame)**, autoCompleteTableHeight))

**Comment by mnbayan** [comment]
See v1.0.1
