### ISSUE TITLE
textFieldDidChange unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by mirzadelic** [mnbayan/AutocompleteTextfieldSwift#8]
I got this error:
![screen shot 2015-06-27 at 10 15 46](https://cloud.githubusercontent.com/assets/1878794/8391135/8f53bca2-1cb5-11e5-94e7-8b4ff1906f7d.png)

Is this my configuration bad or?

**Comment by mnbayan** [comment]
Thank you for reporting this. A fix is coming right away.
