### ISSUE TITLE
How to use with Auto Layout ?

### ISSUE THREAD

**Issue by tjulianb42** [mnbayan/AutocompleteTextfieldSwift#9]
So I wanted to use AutocompleteTextfieldSwift in my project, but I use Autolayout in my Main.storyboard.

I wanted to know how the TableView for results can be below the textfield. Please see the screenshot attached (I set autoCompleteTableHeight to 200.0 in this exemple)

![image](https://cloud.githubusercontent.com/assets/8038925/8393757/83fca01c-1d1e-11e5-8160-ed78a8f0c0cb.png)

Thanks

**Comment by mnbayan** [comment]
@tjulianb42 , could you send me a demo project for where this occured, you can use dropbox. It supposed to work even you used autolayout. The demo project is in autolayout. I'll check your constraints in the demo project you will send me.

**Comment by tjulianb42** [comment]
@mnbayan Yes please see : https://mega.co.nz/#!oAAFXKZb!1_77KwN4yH9ap2aJSu427HPMtwf1jpklSHqKLQlAP1A

**Comment by mnbayan** [comment]
@tjulianb42 The link is not working, download always fails.

**Comment by tjulianb42** [comment]
@mnbayan That's weird, is http://tjulianb.com/ACTF-test.zip or https://www.dropbox.com/s/r7puw5x1mm74y9f/ACTF-test.zip working ?

**Comment by mnbayan** [comment]
@tjulianb42  There is a problem with your constraints. It may look like that it is positioned well in the simulator or your device but the system reads the textfield position as x = 0, y = 0. Opening the storyboard, i found this errors.
![screen shot 2015-07-04 at 7 05 18 pm](https://cloud.githubusercontent.com/assets/8461871/8507750/e3feb8b0-2282-11e5-9c99-3875dd1ea622.png)

I corrected your constraints, please download and take a look https://db.tt/bnvMm4m9. Make sure to add your constraints correctly.

**Comment by tjulianb42** [comment]
@mnbayan Thank you! I'd like to check your corrected project but your link returns me a 404 error

**Comment by mnbayan** [comment]
@tjulianb42 I've edited the link.You should be able to download it now.

**Comment by tjulianb42** [comment]
Thank you so much it works !

**Comment by mnbayan** [comment]
@tjulianb42 You're welcome.
